name: "Labeler"
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  issues:
    types: [opened, edited, labeled]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: "Label PRs and Issues"
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"